# configs/classification/random_forest.yaml

seed: 42

data:
  train: data/processed/train.csv
  valid: data/processed/valid.csv
  test:  data/processed/test.csv

target: "target"

features:
  - feature1
  - feature2
  - feature3

model:
  n_estimators: 300
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  random_state: 42

metrics:
  - accuracy
  - f1
  - roc_auc

reports:
  dir: "reports/random_forest_run"
